### ISSUE TITLE
InflateException on new ZoomSurfaceView

### ISSUE THREAD

**Issue by bkhall** [natario1/ZoomLayout#108] opened 2019-06-11 22:29 UTC
I have an app that already uses an EGL library, which binds to the native libraries.

When implementing a new ZoomSurfaceView, and adding the required com.otaliastudios.opengl:egl-core library, I receive this error from my previously working video player code:

06-11 17:21:10.020 28180-28989/PlayerSDK: nPort=0 bHDecode=0 EGL Version = EGL 1.4 
06-11 17:21:10.021 28180-28989/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x9a145e08) failed (0xffffffea) (already connected to another API?)
06-11 17:21:10.021 28180-28989/libEGL: eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
06-11 17:21:10.021 28180-28989/PlayerSDK: nPort=0 Egl CreateSurface EGL_BAD_ALLOC
06-11 17:21:10.021 28180-28989/PlayerSDK: nPort=0 bHDecode=0 EGL Version = EGL 1.4 
06-11 17:21:10.021 28180-28989/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0x9a145e08) failed (0xffffffea) (already connected to another API?)
06-11 17:21:10.021 28180-28989/libEGL: eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
06-11 17:21:10.021 28180-28989/PlayerSDK: nPort=0 Egl CreateSurface EGL_BAD_ALLOC

However, if I don't include the required egl-core library I get an InflateException telling me to add the library.

Please mod the ZoomSurfaceView code to allow for an EGL implementation other than your own.

Until then, I'll just have to wrap a normal SurfaceView in a ZoomLayout.

**Comment by natario1** [comment] 2019-06-12 00:58
I really can't decode these EGL stacktraces, I don't have experience about it. But it would be cool if you could provide a project that reproduces this issues.

Or try playing yourself with ZoomSurfaceView code and see if you can make this work.

**Comment by bkhall** [comment] 2019-06-12 14:32
The video player SDK I'm using is provided by EZViz (hikvision) here:
https://mvnrepository.com/artifact/com.hikvision.ezviz/ezviz-sdk/4.8.6.2

I can't really provide a sample project though, as their SDK requires a private API key, which clearly I can't share. Even if I could, their SDK is exclusively for use with their cameras -  you'd need one of those along with the API key. It's not a very developer-friendly setup.

I'll play around with it some, but the SurfaceView wrapped in the ZoomLayout is an acceptable solution. However, even that does not work on Marshmallow (6.0.1). I was investigating fixes for that when we ran into this issue. I've looked through your Marshmallow related issues, which appear to be closed, but none of them really address what I'm seeing. On Marshmallow, the wrapped SurfaceView does not zoom or pan.

**Comment by markusressel** [comment] 2020-06-12 21:44
Sadly I don't think there is much we can do about this in regards to the hikvision video player. If this exception is an issue on Marshmallow in general we can open a new issue for that, but I will close this issue for now since there is no way for us to help you :disappointed: . If you happen to find a solution feel free to let us know or open a PR.

**Closed as completed by markusressel** 2020-06-12 21:44 UTC
Labels: is:bug
