### ISSUE TITLE
How to catch click event from ZoomImageView inside ViewPager?

### ISSUE THREAD

**Issue by k1115** [natario1/ZoomLayout#174] opened 2020-07-16 15:42 UTC
### I used setOnTouchListener and catch ACTION_DOWN and ACTION_UP actions for click event

        photoView.setOnTouchListener(object : View.OnTouchListener {
            private var prevActions = emptyList<Int>().toMutableList()
            override fun onTouch(v: View?, event: MotionEvent?): Boolean {
                event?.let {
                    prevActions.add(0, event.action)
                    if (prevActions.size > 5) {
                        prevActions.removeAt(prevActions.size - 1)
                    }
                    if (event.action == ACTION_UP && prevActions.any { it == ACTION_DOWN } &&
                            !prevActions.any { it != ACTION_UP && it != ACTION_DOWN && it != ACTION_MOVE })
                        // Do something
                }
                return false
            }
        })

But on some devices, it's not working properly because multiple events occurs when click.
To enhance it, I needed to increase number 5 from the above code. But it causes bad thing such as occuring click event when fling the image.

Please help me to solve this problem.

**Comment by markusressel** [comment] 2020-07-16 23:34
Hmm... the title states you **cannot** catch events, while the text afterwards suggests that you get multiple events, so which is it? What devices does it work on? What devices does it not work on? Is it API level related? Or is it manufacturer related? What code do you use exactly?

**Comment by k1115** [comment] 2020-07-16 23:37
@markusressel 

Thanks for pay attention.

Sorry, I edited title. Could u please check again?

**Comment by markusressel** [comment] 2020-07-17 00:19
Thx for the update, I am not sure this is caused by this library though, but might be a general behaviour of the touch listener on android. Also, this condition doesn't make much sense to me, what are you trying to achieve with this?

```kotlin
if (event.action == ACTION_UP && prevActions.any { it == ACTION_DOWN } &&
                        !prevActions.any { it != ACTION_UP && it != ACTION_DOWN && it != ACTION_MOVE })
```

**Comment by k1115** [comment] 2020-07-17 00:22
@markusressel 
I am trying to get click behaviour from the above code.
Sorry, Is it possible to enable setOnClickListener on ZoomImageView inside ViewPager?
Maybe if it's enabled, there is no problem.

**Comment by markusressel** [comment] 2020-07-17 00:27
It is possible to use `setOnClickListener` (as is with _any_ `View`), but I think you wont be able to get the exact click location (I might be wrong on this though).

**Comment by k1115** [comment] 2020-07-17 00:32
@markusressel 
Thanks for quick reply. 
I used setOnClickListener but it didn't work.
I think the reason is that it's placed inside ViewPager.

**Comment by markusressel** [comment] 2020-07-17 00:48
I'm sorry, but I probably can't help you with that. I can only tell you that the touch and onclick listeners work the same way as they do with any other `View` in android. If they are not called the event is probably catched by a parent view and not passed on to the child. Otherwise, if you get more touch events than expected, you could try and debug where these events are coming from, but this library does not generate artificial events for sure, so it is probably not related to this library, but to android itself.

**Comment by k1115** [comment] 2020-07-17 01:39
@markusressel 
Okay. I will research more on that way.
Really appreciate for your help.

**Comment by markusressel** [comment] 2020-07-17 04:34
No worries.
I will close this issue for now, if you feel like a followup is necessary, feel free to comment or open a new issue.

**Closed as completed by markusressel** 2020-07-17 04:34 UTC
Labels: is:question
